'use strict'

const routesLog = require('./log')
const routesUser = require('./user')
const routesSale = require('./sale')
const routesReceipt = require('./receipt')
const routesVoucher = require('./voucher')
const routesCategory = require('./category')
const routesTemplate = require('./template')
const routesWhatsapp = require('./whatsapp')
const routesAgreement = require('./agreement')
const routesCall = require('./call')
const routesEmail = require('./email')
const routesProgress = require('./progress')
const routesCourse = require('./course')
const routesMigrate = require('./migration')
const routesContact = require('./contact')
const routesNotification = require('./notifications')
const routesTimeline = require('./timeline')
const routesPayment = require('./payment')
const routesMeta = require('./meta')
const routesMoodle = require('./moodle')

module.exports = server => {
  server.use('/api', routesLog)
  server.use('/api', routesUser)
  server.use('/api', routesWhatsapp)
  server.use('/api', routesReceipt)
  server.use('/api', routesSale)
  server.use('/api', routesAgreement)
  server.use('/api', routesVoucher)
  server.use('/api', routesCategory)
  server.use('/api', routesTemplate)
  server.use('/api', routesCall)
  server.use('/api', routesEmail)
  server.use('/api', routesProgress)
  server.use('/api', routesCourse)
  server.use('/api', routesMigrate)
  server.use('/api', routesContact)
  server.use('/api', routesNotification)
  server.use('/api', routesTimeline)
  server.use('/api', routesPayment)
  server.use('/api', routesMeta)
  server.use('/api', routesMoodle)
}
